# 线性代数
numpy 提供线性代数所需的所有功能

    dot           两个数组的点积,对应元素相乘
    vdot          两个向量的点积
    inner         两个数组的内积
    
    matmul        两个数组的矩阵积
    determinant   数组的行列式
    solve         求解线性矩阵方程
    inv           计算矩阵的乘法逆矩阵


In [9]:
import numpy as np 
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])
# 矩阵乘积
print(np.dot(a,b))
print(1*5+2*7,1*6+2*8)
print(3*5+4*7,3*6+4*8)
# 点积
print(np.vdot(a,b))
print(1*5+2*6+3*7+4*8)


print('-----')
# 内积
print(np.inner(a,b))
print(1*5+2*6,1*7+2*8)
print(3*5+4*6,3*7+4*8)

[[19 22]
 [43 50]]
19 22
43 50
70
70
-----
[[17 23]
 [39 53]]
17 23
39 53


* 矩阵
    1*5+2*7,1*6+2*8
    3*5+4*7,3*6+4*8
* 点积
    1*3+2*4+5*7+6*8


In [10]:
# 行列式
import numpy as np 
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])
print(np.linalg.det(a))



-2.0000000000000004


In [11]:
import numpy as np 
a = np.array([[1,1,1],[0,2,5],[2,5,-1]]) 
 
print ('数组 a：')
print (a)
ainv = np.linalg.inv(a) 
 
print ('a 的逆：')
print (ainv)
 
print ('矩阵 b：')
b = np.array([[6],[-4],[27]]) 
print (b)
 
print ('计算：A^(-1)B：')
x = np.linalg.solve(a,b) 
print (x)
# 这就是线性方向 x = 5, y = 3, z = -2 的解

数组 a：
[[ 1  1  1]
 [ 0  2  5]
 [ 2  5 -1]]
a 的逆：
[[ 1.28571429 -0.28571429 -0.14285714]
 [-0.47619048  0.14285714  0.23809524]
 [ 0.19047619  0.14285714 -0.0952381 ]]
矩阵 b：
[[ 6]
 [-4]
 [27]]
计算：A^(-1)B：
[[ 5.]
 [ 3.]
 [-2.]]
