# NumPy 广播(broadcast)
* 对不同形状的数组进行数值计算额方式


In [3]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a*b
print("a*b" , c)
d = a+b
print("a+b" , d)


a*b [ 10  40  90 160]
a+b [11 22 33 44]


In [16]:
import numpy as np
a = np.arange(1,11,1).reshape(2,5)
print(a)
b = np.random.randint(1,5,(2,1))
print(b)
c = a+b 
print("a+b\n",c)
d = a*b
print("a*c\n",d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1]
 [4]]
a+b
 [[ 2  3  4  5  6]
 [10 11 12 13 14]]
a*c
 [[ 1  2  3  4  5]
 [24 28 32 36 40]]


## 广播
当前维度一个为1 ,其他值相等


In [23]:
# nditer 迭代
import numpy as np 
a = np.arange(6).reshape(2,3)
for i in np.nditer(a):
    print("%d\t"%(i),end='')
print('\n')
# 列优先
for i in np.nditer(a,order='F'):
    print("%d\t"%(i),end='')
print('\n')

0	1	2	3	4	5	

0	3	1	4	2	5	



In [24]:
import numpy as np 
a = np.arange(6)
a[2] = 10
print(a)

[ 0  1 10  3  4  5]


In [30]:
import numpy as np 
a = np.random.rand(6).reshape(2,3)
print(a)

# 返回数组
print(a.ravel())

for row in a:
    print(row)

# 数组中每隔元素处理
for element in a.flat:
    print(element)

[[0.4186971  0.70295061 0.36730404]
 [0.39977241 0.11530359 0.04168465]]
[0.4186971  0.70295061 0.36730404 0.39977241 0.11530359 0.04168465]
[0.4186971  0.70295061 0.36730404]
[0.39977241 0.11530359 0.04168465]
0.4186971029988341
0.7029506105776234
0.3673040350644663
0.39977240515791856
0.11530358713658684
0.041684653840171726


In [37]:
import numpy as np
a = np.random.randint(1,10,(2,5))
print(a)
# np.transpose(a) == a.T 转置  
print(np.transpose(a))
print(a.T)


[[2 3 1 5 3]
 [1 8 3 7 4]]
[[2 1]
 [3 8]
 [1 3]
 [5 7]
 [3 4]]
[[2 1]
 [3 8]
 [1 3]
 [5 7]
 [3 4]]


In [38]:
num = np.random.randn(6).reshape(2,3)
print(num)
print(np.abs(num))
print(np.fabs(num))

[[ 0.4445191   0.46108757 -0.86727162]
 [-0.88658369 -0.66930969 -0.63602087]]
[[0.4445191  0.46108757 0.86727162]
 [0.88658369 0.66930969 0.63602087]]
[[0.4445191  0.46108757 0.86727162]
 [0.88658369 0.66930969 0.63602087]]


In [47]:
a = np.random.randint(1,10,(2,3))
print(a)
# np.sqrt 平方根  np.square 平方
print(np.sqrt(a))
print(np.square(a))

# 自然底数 e的n次方
print('exp\n',np.exp(a))
# 自然对数
print('log\n',np.log(a))
print('')

[[4 6 8]
 [7 9 5]]
[[2.         2.44948974 2.82842712]
 [2.64575131 3.         2.23606798]]
[[16 36 64]
 [49 81 25]]
exp
 [[  54.59815003  403.42879349 2980.95798704]
 [1096.63315843 8103.08392758  148.4131591 ]]
log
 [[1.38629436 1.79175947 2.07944154]
 [1.94591015 2.19722458 1.60943791]]
