## numpy
1. 支持大量维度数组和矩阵运算
2. 提供大量数学函数库
3. 开源

In [2]:
# Ndarray N维数组对象
import numpy as np
# 一维数组
a = np.array([1,2,3])
print(a)
b = np.array([[1,2],[3,4]])
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


# 参数:
     object:数组或者嵌套的数列 必存在
     dtype :数据类型
     copy  :
     order :创建数组的方向  C 行  F 列   A 任意方向
     subok :
     ndmin :指定生成数组的最小维度

In [11]:
import numpy as np
a = np.empty((2,2),dtype = 'i1')
print("empty",a)
b = np.zeros((2,2),dtype = 'i4')
print("zeros",b)
c = np.ones((2,2),dtype = 'i4')
print("ones" , c)


empty [[1 0]
 [0 0]]
zeros [[0 0]
 [0 0]]
ones [[1 1]
 [1 1]]


In [13]:
# 数组转ndarray
a = np.array([1,3,4])
print(a)

[1 3 4]


In [25]:
a = np.linspace(1,5,3)
print(a)
b = np.logspace(1,5,5,base=2)
print(b)

[1. 3. 5.]
[ 2.  4.  8. 16. 32.]


```
    numpy.linspace 等差数列
    numpy.linspace(start,stop,num,endpoint,retstep,dtype)
    start 起始值
    stop  结束值
    num   生成等间隔样例的数量，默认为50
    endpoint 序列中是否包含stop 值 默认为 True
    
    numpy.logspace 等比数列
        numpy.logscale(start, stop, num, endpoint, base, dtype)
    1.	start 起始值是base ** start
    2.	stop 终止值是base ** stop
    3.	num 范围内的数值数量，默认为50
    4.	endpoint 如果为true，终止值包含在输出数组当中
    5.	base 对数空间的底数，默认为10
    6.	dtype 输出数组的数据类型，如果没有提供，则取决于其它参数
```

In [26]:
a = np.random.rand(9).reshape(3,3)
print(a)

[[0.78530743 0.39422449 0.95726152]
 [0.26335087 0.79406296 0.76026831]
 [0.8481331  0.37991364 0.76312638]]


In [28]:
a = np.random.rand(3,2)
print(a)

[[0.05516145 0.6101265 ]
 [0.43452718 0.92168552]
 [0.44579177 0.66416713]]


In [32]:
a = np.random.random((2,3))
print(a)

[[0.12186265 0.69461913 0.77414919]
 [0.40649368 0.33759928 0.28304661]]



    ## 其他创建方式
    random模块
    rand  返回 0 - 1 随机值
    randn 返回一个样本具有标准正态分布
    randint 返回随机的整数，位于半开区间[low,hight)size = 10  (3,3)
    random_integers(low[, high, size])  返回随机的整数，位于闭区间
    random 返回随机浮点数


In [41]:
a = np.array([[1,2,3],[4,5,6]],dtype = 'i1')
print(a)
print(a.shape)
print(type(a.shape))
# b = a.reshape(3,2)   -1自动算出
b = a.reshape(-1,2)
print(b)
# ndim 维数
print(b.shape , b.ndim)
# itemsize 单个元素内存大小  size数组个数 
print(b.itemsize , b.size)

[[1 2 3]
 [4 5 6]]
(2, 3)
<class 'tuple'>
[[1 2]
 [3 4]
 [5 6]]
(3, 2) 2
1 6


In [47]:
a = np.random.randint(1,100,size=(3,4))
print(a)
print(a[1][2:])
# 切片后类型不变
print(type(a[1][2:]))

[[20 50 15 22]
 [54 82 92 71]
 [99 65 96 39]]
[92 71]
<class 'numpy.ndarray'>
